version: 1.2
workflows:

   - name: "sldsc"
     subclass: WDL
     primaryDescriptorPath: /sldsc.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "calculate_ldscores"
     subclass: WDL
     primaryDescriptorPath: /ld_scores.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "regression"
     subclass: WDL
     primaryDescriptorPath: /regression.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/
