version: 1.2
workflows:
   - name: "sldsc_regression_full"
     subclass: WDL
     primaryDescriptorPath: /sldsc.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "calculate_ldscores"
     subclass: WDL
     primaryDescriptorPath: /workflows/subwf-ld_scores.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/

   - name: "regression"
     subclass: WDL
     primaryDescriptorPath: /regression.wdl
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/
