version: 1.2
workflows:
   - name: "calculate_ldscores"
     subclass: WDL
     primaryDescriptorPath: /ld_scores.wdl
     filters: 
        branches: 
          - main
        tags: 
          - /.*/
